name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  intl_phone_field: ^3.2.0
  pdf: ^3.10.8
  printing: ^5.12.0

  supabase_flutter: ^2.10.0
  image_picker: ^1.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  image: ^4.5.4

  provider: ^6.1.1
  http: ^1.1.0
  http_parser: ^4.0.2

  mime: ^2.0.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
